import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Next.jsに最初からgoogleフォントの機能が組み込まれている
import "./globals.css";
import { cn } from "@/lib/utils";
import Link from 'next/link'; // "next/link"から"Link"コンポーネントをインポート
import { Button } from "@/components/ui/button" // Buttonをインポート
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/mode-toggle";

const inter = Inter({ subsets: ["latin"] }); // NextFont

// タイトル（タブ名、検索結果）の設定
export const metadata: Metadata = {
  title: {
    template: "%s | cosugi",
    default: "cosugi",
  },
  description: "Generated by create next app",
};

// 'nav'の'li'3つをオブジェクトでまとめる
const navItems = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about' },
  { label: 'Contact', href: '/contact' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>

      <body className={cn(inter.className, "min-h-dvh")}> {/* Reactで変数を結合したい場合、cn(,)を使う */}
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <header className="container h-16 flex items-center border-b justify-between">
          <h1 className="font-bold">LOGO</h1>
          <nav>
            <ul className="flex gap-4">
              {navItems.map(item => (
                <li key={item.label}>
                  <Button variant="ghost" asChild>
                    <Link href={item.href}>{item.label}</Link>
                  </Button>
                </li>
              ))}
            </ul>
          </nav>
        </header>

        <main>
          {children}
        </main>

        <footer className="container sticky top-full h-16 flex justify-between items-center border-t">
          <p>&copy; cosugi</p>
          
          <ModeToggle />
        </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
